# srcs/docker-compose.yml
version: '3.8'

services:
  mariadb:
    build: requirements/mariadb
    secrets:
    - mysql_database
    - mysql_user
    - mysql_root_password
    - mysql_password
    container_name: mariadb
    restart: always
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h mariadb -u$$(cat /run/secrets/mysql_user) -p$$(cat /run/secrets/mysql_password)"]
      timeout: 20s
      retries: 10
      interval: 5s
      start_period: 10s


  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    secrets:
    - mysql_database
    - mysql_user
    - mysql_password      
    - wp_admin_password
    - wp_user_password
    restart: always
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    depends_on:
      mariadb:
        condition: service_healthy

  nginx:
    container_name: nginx
    build: requirements/nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    depends_on:
      - wordpress

secrets:
  mysql_database:
    file: ../secrets/mysql_database
  mysql_user:
    file: ../secrets/mysql_user
  mysql_root_password:
    file: ../secrets/mysql_root_password
  mysql_password:
    file: ../secrets/mysql_password
  wp_admin_password:
    file: ../secrets/wp_admin_password
  wp_user_password:
    file: ../secrets/wp_user_password

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress

networks:
  inception_network:
    driver: bridge